<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite" duration-ms="79" started-at="2015-11-18T07:38:12Z" finished-at="2015-11-18T07:38:12Z">
    <groups>
    </groups>
    <test name="SmokeTest" duration-ms="36" started-at="2015-11-18T07:38:12Z" finished-at="2015-11-18T07:38:12Z">
      <class name="com.invoke.test.TestA">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.invoke.test.TestA@33ddcf6e]" name="setup" is-config="true" duration-ms="10" started-at="2015-11-18T15:38:12Z" finished-at="2015-11-18T15:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.invoke.test.TestA@33ddcf6e]" name="test1" duration-ms="4" started-at="2015-11-18T15:38:12Z" finished-at="2015-11-18T15:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:com.invoke.test.TestA@33ddcf6e]" name="test2" duration-ms="3" started-at="2015-11-18T15:38:12Z" finished-at="2015-11-18T15:38:12Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertFalse(Assert.java:34)
	at junit.framework.Assert.assertFalse(Assert.java:41)
	at com.invoke.test.TestA.test2(TestA.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="test3()[pri:0, instance:com.invoke.test.TestA@33ddcf6e]" name="test3" duration-ms="0" started-at="2015-11-18T15:38:12Z" depends-on-methods="com.invoke.test.TestA.test2" finished-at="2015-11-18T15:38:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestA.test3()[pri:0, instance:com.invoke.test.TestA@33ddcf6e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestA.test3()[pri:0, instance:com.invoke.test.TestA@33ddcf6e] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="clearup()[pri:0, instance:com.invoke.test.TestA@33ddcf6e]" name="clearup" is-config="true" duration-ms="0" started-at="2015-11-18T15:38:12Z" finished-at="2015-11-18T15:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearup -->
      </class> <!-- com.invoke.test.TestA -->
    </test> <!-- SmokeTest -->
    <test name="2est" duration-ms="12" started-at="2015-11-18T07:38:12Z" finished-at="2015-11-18T07:38:12Z">
      <class name="com.invoke.test.TestB">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.invoke.test.TestB@56d0c5bb]" name="setup" is-config="true" duration-ms="1" started-at="2015-11-18T15:38:12Z" finished-at="2015-11-18T15:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.invoke.test.TestB@56d0c5bb]" name="test1" duration-ms="1" started-at="2015-11-18T15:38:12Z" finished-at="2015-11-18T15:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.invoke.test.TestB@56d0c5bb]" name="test2" duration-ms="1" started-at="2015-11-18T15:38:12Z" depends-on-methods="com.invoke.test.TestB.test1" finished-at="2015-11-18T15:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test3()[pri:0, instance:com.invoke.test.TestB@56d0c5bb]" name="test3" duration-ms="0" started-at="2015-11-18T15:38:12Z" depends-on-methods="com.invoke.test.TestB.test2" finished-at="2015-11-18T15:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="clearup()[pri:0, instance:com.invoke.test.TestB@56d0c5bb]" name="clearup" is-config="true" duration-ms="1" started-at="2015-11-18T15:38:12Z" finished-at="2015-11-18T15:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearup -->
      </class> <!-- com.invoke.test.TestB -->
    </test> <!-- 2est -->
  </suite> <!-- TestSuite -->
</testng-results>
